---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "nanotranslate"
description: a local tool biopython based to translate flash output
keywords:
  - nanobodies
  - translation
  - genomics
tools:
  - "nanotranslate":
      description: "Freely available tools for computational molecular biology."
      homepage: "https://biopython.org/"
      documentation: "https://biopython.org/"
      tool_dev_url: "https://biopython.org/"
      licence: ['Biopython License Agreement']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - mergedfq:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - single_end:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"


output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - fasta:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - log:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
authors:
  - "@davidebag"
maintainers:
  - "@davidebag"
