---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "rename"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "quay.io/biocontainers/fastx_toolkit:0.0.13--0"
